---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    calibre_web_automated_traefik_enable: false
  tasks:
    - name: Include calibre_web_automated role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.calibre_web_automated
