collections:
  - name: ansible.posix
    version: ">=2.0,<2.1"

  - name: ansible.utils
    version: ">=6.0,<7"

  - name: bitwarden.secrets
    version: ">=1.0,<1.1"

  - name: community.crypto
    version: ">=3.0,<3.1"

  - name: community.digitalocean
    version: ">=1.27,<1.28"

  - name: community.docker
    version: ">=4.7,<4.8"

  - name: community.general
    version: ">=11.0,<11.1"

  - name: containers.podman
    version: ">=1.17,<1.18"

  - name: pfsensible.core
    version: ">=0.7,<0.8"

  - name: pfsensible.haproxy
    version: ">=0.1,<0.2"
