---
# handlers file for jaredhocutt.homelab.board_game_tracker

- name: Restart {{ board_game_tracker_name }}
  ansible.builtin.systemd:
    name: "{{ board_game_tracker_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart postgres for {{ board_game_tracker_name }}
  ansible.builtin.systemd:
    name: "{{ board_game_tracker_name }}-postgres.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
