---
# vars file for jaredhocutt.homelab.shelfmark

###############################################################################
# Envrionment
###############################################################################

shelfmark_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

shelfmark_secrets_defaults: {}

shelfmark_secrets_combined: >-
  {{ shelfmark_secrets_defaults
  | combine(shelfmark_secrets, recursive=True) }}

shelfmark_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

shelfmark_container_labels_defaults: >
  {{ shelfmark_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', shelfmark_name, shelfmark_traefik_host, '8084'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

shelfmark_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
