---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    changedetection_traefik_enable: false
  tasks:
    - name: Include changedetection role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.changedetection
