---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    audiobookshelf_traefik_enable: false
  tasks:
    - name: Include audiobookshelf role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.audiobookshelf
