---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    lubelogger_traefik_enable: false
  tasks:
    - name: Include lubelogger role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.lubelogger
