---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    shelfmark_traefik_enable: false
  tasks:
    - name: Include shelfmark role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.shelfmark
