---
# vars file for jaredhocutt.homelab.stirling_pdf

###############################################################################
# Envrionment
###############################################################################

stirling_pdf_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

stirling_pdf_secrets_defaults: {}

stirling_pdf_secrets_combined: >-
  {{ stirling_pdf_secrets_defaults
  | combine(stirling_pdf_secrets, recursive=True) }}

stirling_pdf_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

stirling_pdf_container_labels_defaults: >
  {{ stirling_pdf_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', stirling_pdf_name, stirling_pdf_traefik_host, '8080'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

stirling_pdf_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
