---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    it_tools_traefik_enable: false
  tasks:
    - name: Include it_tools role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.it_tools
