---

ansible_python_interpreter: python3

###############################################################################
# backrest
###############################################################################

backrest_version: v1.11.2

backrest_traefik_enable: false

backrest_env:
  BACKREST_PORT: 0.0.0.0:9898

###############################################################################
# pangolin
###############################################################################

pangolin_image_tag: "ee-1.18.4"  # skopeo list-tags docker://docker.io/fosrl/pangolin | jq -r '.Tags[] | select(test("^ee-[0-9\\.]+$"))'
pangolin_gerbil_image_tag: "1.4.1"  # skopeo list-tags docker://docker.io/fosrl/gerbil | jq -r '.Tags[] | select(test("^[0-9]\\."))'
pangolin_traefik_image_tag: v3.7.4  # skopeo list-tags docker://docker.io/library/traefik | jq -r '.Tags[] | select(test("^v[0-9\\.]+$"))'

pangolin_gerbil_ports_extra:
  - 8211:8211/udp  # pangolin

pangolin_base_domain: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_base_domain') }}"
pangolin_server_secret: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_server_secret') }}"
pangolin_traefik_letsencrypt_email: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_no_reply') }}"

pangolin_smtp_host: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_host') }}"
pangolin_smtp_port: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_port') }}"
pangolin_smtp_user: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_user') }}"
pangolin_smtp_password: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_password') }}"
pangolin_no_reply: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_smtp_no_reply') }}"

###############################################################################
# pangolin_cli
###############################################################################

pangolin_cli_image_tag: "0.9.0"  # skopeo list-tags docker://docker.io/fosrl/pangolin-cli | jq -r '.Tags[] | select(test("^[0-9\\.]+$"))'

pangolin_cli_endpoint: https://pangolin.{{ lookup('jaredhocutt.homelab.bws', 'pangolin_base_domain') }}

pangolin_cli_secrets:
  pangolin_cli_client_id: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_cli_edge_client_id') }}"
  pangolin_cli_client_secret: "{{ lookup('jaredhocutt.homelab.bws', 'pangolin_cli_edge_client_secret') }}"
pangolin_cli_container_secrets:
  - pangolin_cli_client_id,type=env,target=CLIENT_ID
  - pangolin_cli_client_secret,type=env,target=CLIENT_SECRET

###############################################################################
# server_setup
###############################################################################

server_setup_dnf_automatic: true
server_setup_fail2ban: true

###############################################################################
# cloudflare
###############################################################################

cloudflare_zone: "{{ lookup('jaredhocutt.homelab.bws', 'cloudflare_zone') }}"

###############################################################################
# digitalocean_droplet
###############################################################################

droplet_region: nyc3
droplet_image: fedora-43-x64
droplet_size: s-2vcpu-2gb-90gb-intel

droplet_ssh_keys:
  - "{{ lookup('jaredhocutt.homelab.bws', 'ssh_authorized_key_1') }}"
  - "{{ lookup('jaredhocutt.homelab.bws', 'ssh_authorized_key_2') }}"

droplet_user_data: |
  #cloud-config
  write_files:
    - path: /etc/sudoers.d/99-custom-defaults
      owner: root:root
      permissions: '0440'
      content: |
        Defaults:{{ lookup('jaredhocutt.homelab.bws', 'server_user_2_username') }} !requiretty

  users:
    - name: {{ lookup('jaredhocutt.homelab.bws', 'server_user_1_username') }}
      gecos: {{ lookup('jaredhocutt.homelab.bws', 'server_user_1_fullname') }}
      uid: {{ lookup('jaredhocutt.homelab.bws', 'server_user_1_uid') }}
      groups: {{ lookup('jaredhocutt.homelab.bws', 'server_user_1_groups') }}
      passwd: {{ lookup('jaredhocutt.homelab.bws', 'server_user_1_password_crypted') }}
      lock_passwd: false
      ssh_authorized_keys:
        - {{ lookup('jaredhocutt.homelab.bws', 'ssh_authorized_key_1') }}
        - {{ lookup('jaredhocutt.homelab.bws', 'ssh_authorized_key_2') }}
    - name: {{ lookup('jaredhocutt.homelab.bws', 'server_user_2_username') }}
      gecos: {{ lookup('jaredhocutt.homelab.bws', 'server_user_2_fullname') }}
      uid: {{ lookup('jaredhocutt.homelab.bws', 'server_user_2_uid') }}
      groups: {{ lookup('jaredhocutt.homelab.bws', 'server_user_2_groups') }}
      sudo:
        - "ALL=(ALL) NOPASSWD:ALL"
      lock_passwd: true
      ssh_authorized_keys:
        - {{ lookup('jaredhocutt.homelab.bws', 'ssh_authorized_key_4') }}

  # The Fedora image in Digital Ocean is broken for journald
  runcmd:
    - |
      machine_id=$(cat /etc/machine-id)
      for dir in /var/log/journal/*/; do
        dirname=$(basename "$dir")
        if [ "$dirname" != "$machine_id" ]; then
          mv "$dir" "/var/log/journal/$machine_id"
        fi
      done
      systemctl restart systemd-journald

###############################################################################
# digitalocean_firewall
###############################################################################

digitalocean_firewall_default_inbound_rules:
  - protocol: tcp
    ports: "22"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: icmp
    ports: "0"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"

digitalocean_firewall_default_outbound_rules:
  - protocol: tcp
    ports: "0"
    destinations:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: udp
    ports: "0"
    destinations:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: icmp
    ports: "0"
    destinations:
      addresses:
        - "0.0.0.0/0"
        - "::/0"

digitalocean_firewall_pangolin_inbound_rules:
  - protocol: tcp
    ports: "80"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: tcp
    ports: "443"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: udp
    ports: "21820"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: udp
    ports: "51820"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
  - protocol: udp
    ports: "8211"
    sources:
      addresses:
        - "0.0.0.0/0"
        - "::/0"
