---

all:
  hosts:
    localhost:
      ansible_host: localhost
    apps:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_apps') }}"
    edge: {}
    pta:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_pta') }}"
    pta_edge: {}
    router:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_router') }}"

linux:
  hosts:
    apps: {}
    edge: {}
    pta: {}
    pta_edge: {}
network:
  hosts:
    router: {}
