---

all:
  hosts:
    localhost:
      ansible_host: localhost
    router:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_router') }}"
    apps:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_apps') }}"
    media:
      ansible_host: "{{ lookup('jaredhocutt.homelab.bws', 'ansible_host_media') }}"
    edge: {}

linux:
  hosts:
    apps: {}
    media: {}
    edge: {}
network:
  hosts:
    router: {}
