---
# vars file for jaredhocutt.homelab.sonarr

###############################################################################
# Envrionment
###############################################################################

sonarr_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

sonarr_secrets_defaults: {}

sonarr_secrets_combined: >-
  {{ sonarr_secrets_defaults
  | combine(sonarr_secrets, recursive=True) }}

sonarr_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

sonarr_container_labels_defaults: >
  {{ sonarr_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', sonarr_name, sonarr_traefik_host, '8989'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

sonarr_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
