---
# vars file for jaredhocutt.homelab.wizarr

###############################################################################
# Envrionment
###############################################################################

wizarr_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

wizarr_secrets_defaults: {}

wizarr_secrets_combined: >-
  {{ wizarr_secrets_defaults
  | combine(wizarr_secrets, recursive=True) }}

wizarr_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

wizarr_container_labels_defaults: >
  {{ wizarr_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', wizarr_name, wizarr_traefik_host, '5690'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

wizarr_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
