---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    nocodb_traefik_enable: false
    nocodb_postgres_password: test-postgres-password
  tasks:
    - name: Include nocodb role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.nocodb
