---
# tasks file for jaredhocutt.homelab.pangolin_cli

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ pangolin_cli_image }}"
      image_tag: "{{ pangolin_cli_image_tag }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  no_log: true
  loop: "{{ pangolin_cli_secrets_combined | dict2items }}"

- name: Create pangolin_cli container
  containers.podman.podman_container:
    name: "{{ pangolin_cli_name }}"
    image: "{{ pangolin_cli_image }}:{{ pangolin_cli_image_tag }}"
    network: host
    env: "{{ lookup('jaredhocutt.homelab.container_config', 'env') }}"
    secrets: "{{ lookup('jaredhocutt.homelab.container_config', 'secrets') }}"
    cap_add:
      - NET_ADMIN
    device:
      - /dev/net/tun:/dev/net/tun
    labels: "{{ lookup('jaredhocutt.homelab.container_config', 'labels') }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ lookup('jaredhocutt.homelab.container_config', 'quadlet_options') }}"
    state: quadlet
  notify: Restart {{ pangolin_cli_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
