---

- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf5-plugin-automatic
    state: present
  become: true

- name: Configure dnf-automatic
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable and start dnf-automatic.timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: started
    enabled: true
  become: true
