---

- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present
  become: true

- name: Configure fail2ban
  ansible.builtin.template:
    src: fail2ban-sshd.conf.j2
    dest: /etc/fail2ban/jail.d/sshd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
