---
# vars file for jaredhocutt.homelab.immich

immich_postgres_db_name: immich
immich_postgres_user: immich

###############################################################################
# Envrionment
###############################################################################

immich_container_env_defaults:
  DB_HOSTNAME: "{{ immich_name }}-postgres"
  REDIS_HOSTNAME: "{{ immich_name }}-redis"

immich_machine_learning_container_env_defaults: {}

immich_postgres_container_env_defaults:
  POSTGRES_INITDB_ARGS: --data-checksums

immich_redis_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

immich_secrets_defaults:
  immich_postgres_db_name: "{{ immich_postgres_db_name }}"
  immich_postgres_user: "{{ immich_postgres_user }}"
  immich_postgres_password: "{{ immich_postgres_password }}"

immich_secrets_combined: >-
  {{ immich_secrets_defaults
  | combine(immich_secrets, recursive=True) }}

immich_container_secrets_defaults:
  - immich_postgres_db_name,type=env,target=DB_DATABASE_NAME
  - immich_postgres_user,type=env,target=DB_USERNAME
  - immich_postgres_password,type=env,target=DB_PASSWORD

immich_machine_learning_container_secrets_defaults:
  - immich_postgres_db_name,type=env,target=DB_DATABASE_NAME
  - immich_postgres_user,type=env,target=DB_USERNAME
  - immich_postgres_password,type=env,target=DB_PASSWORD

immich_postgres_container_secrets_defaults:
  - immich_postgres_db_name,type=env,target=POSTGRES_DB
  - immich_postgres_user,type=env,target=POSTGRES_USER
  - immich_postgres_password,type=env,target=POSTGRES_PASSWORD

immich_redis_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

immich_container_labels_defaults: >
  {{ immich_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', immich_name, immich_traefik_host, '2283'), {}) }}

immich_machine_learning_container_labels_defaults: {}

immich_postgres_container_labels_defaults: {}

immich_redis_container_labels_defaults: {}

###############################################################################
# Quadlet Options
###############################################################################

immich_quadlet_options_depends:
  - |
    [Unit]
    Requires={{ immich_name }}-postgres.service
    Requires={{ immich_name }}-redis.service
    After={{ immich_name }}-postgres.service
    After={{ immich_name }}-redis.service
immich_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults + immich_quadlet_options_depends }}"

immich_machine_learning_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

immich_postgres_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"

immich_redis_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
