# Molecule managed
FROM {{ item.image }}

# Keep systemd host-like, but skip units that expect a real booted machine.
RUN dnf --assumeyes install /usr/bin/python3-config systemd \
  && systemctl --root=/ set-default multi-user.target \
  && systemctl --root=/ disable \
       getty.target \
       systemd-logind.service \
       systemd-user-sessions.service \
       systemd-udevd.service \
       systemd-udev-trigger.service \
  && dnf clean all

VOLUME [ "/sys/fs/cgroup" ]

STOPSIGNAL SIGRTMIN+3

CMD [ "/usr/sbin/init" ]
