---
# vars file for jaredhocutt.homelab.portainer

###############################################################################
# Envrionment
###############################################################################

portainer_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

portainer_secrets_defaults: {}

portainer_secrets_combined: >-
  {{ portainer_secrets_defaults
  | combine(portainer_secrets, recursive=True) }}

portainer_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

portainer_container_labels_defaults: >
  {{ portainer_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', portainer_name, portainer_traefik_host, '9443'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

portainer_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
