---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    radarr_traefik_enable: false
  tasks:
    - name: Include radarr role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.radarr
