---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    bentopdf_traefik_enable: false
  tasks:
    - name: Include bentopdf role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.bentopdf
