---
# vars file for jaredhocutt.homelab.bentopdf

###############################################################################
# Envrionment
###############################################################################

bentopdf_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

bentopdf_secrets_defaults: {}

bentopdf_secrets_combined: >-
  {{ bentopdf_secrets_defaults
  | combine(bentopdf_secrets, recursive=True) }}

bentopdf_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

bentopdf_container_labels_defaults: >-
  {{ bentopdf_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', bentopdf_name, bentopdf_traefik_host, '8080'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

bentopdf_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
