---
# defaults file for jaredhocutt.homelab.youtarr

youtarr_name: youtarr

youtarr_image: docker.io/dialmaster/youtarr
youtarr_image_tag: latest
youtarr_mariadb_image: docker.io/library/mariadb
youtarr_mariadb_image_tag: "11"

youtarr_volume_config: "{{ youtarr_name }}-config"
youtarr_volume_jobs: "{{ youtarr_name }}-jobs"
youtarr_volume_images: "{{ youtarr_name }}-images"
youtarr_volume_media: "{{ youtarr_name }}-media"
youtarr_mariadb_volume_data: "{{ youtarr_name }}-mariadb-data"

youtarr_traefik_enable: true
youtarr_traefik_host: "{{ youtarr_name }}.{{ common_traefik_domain }}"
youtarr_ports:
  - 3087:3011

youtarr_secrets: {}

youtarr_container_env: {}
youtarr_container_secrets: []
youtarr_container_labels: {}
youtarr_container_quadlet_options: []

youtarr_mariadb_container_env: {}
youtarr_mariadb_container_secrets: []
youtarr_mariadb_container_labels: {}
youtarr_mariadb_container_quadlet_options: []

youtarr_media_path: /usr/src/app/data
