---
# tasks file for jaredhocutt.homelab.n8n

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item.image }}:{{ item.image_tag }}"
    state: present
  become: true
  loop:
    - image: "{{ n8n_image }}"
      image_tag: "{{ n8n_image_tag }}"
    - image: "{{ n8n_postgres_image }}"
      image_tag: "{{ n8n_postgres_image_tag }}"
    - image: "{{ n8n_redis_image }}"
      image_tag: "{{ n8n_redis_image_tag }}"

- name: Create network
  containers.podman.podman_network:
    name: "{{ n8n_name }}"
    driver: bridge
    disable_dns: false
    opt:
      isolate: "true"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true

- name: Create volumes
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    quadlet_options: "{{ item.options | default(omit) }}"
    quadlet_file_mode: "0600"
    state: quadlet
  become: true
  loop:
    - name: "{{ n8n_volume_data }}"
      options: "{{ n8n_volume_data_options | default(omit) }}"
    - name: "{{ n8n_postgres_volume_data }}"
      options: "{{ n8n_postgres_volume_data_options | default(omit) }}"
    - name: "{{ n8n_redis_volume_data }}"
      options: "{{ n8n_redis_volume_data_options | default(omit) }}"

- name: Create secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    data: "{{ item.value }}"
    state: present
  become: true
  loop: "{{ n8n_secrets_combined | dict2items }}"

- name: Create postgres container
  containers.podman.podman_container:
    name: "{{ n8n_name }}-postgres"
    image: "{{ n8n_postgres_image }}:{{ n8n_postgres_image_tag }}"
    network: "{{ n8n_name }}.network"
    env: "{{ lookup('jaredhocutt.homelab.container_config', 'env', container='postgres') }}"
    secrets: "{{ lookup('jaredhocutt.homelab.container_config', 'secrets', container='postgres') }}"
    volumes:
      - "{{ n8n_postgres_volume_data }}.volume:/var/lib/postgresql/data"
    healthcheck_interval: 30s
    healthcheck_retries: 5
    healthcheck_start_period: 20s
    healthcheck_timeout: 5s
    healthcheck: CMD-SHELL pg_isready -d {{ n8n_postgres_db_name }} -U {{ n8n_postgres_user }}
    labels: "{{ lookup('jaredhocutt.homelab.container_config', 'labels', container='postgres') }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ lookup('jaredhocutt.homelab.container_config', 'quadlet_options', container='postgres') }}"
    state: quadlet
  notify: Restart postgres for {{ n8n_name }}
  become: true

- name: Create redis container
  containers.podman.podman_container:
    name: "{{ n8n_name }}-redis"
    image: "{{ n8n_redis_image }}:{{ n8n_redis_image_tag }}"
    network: "{{ n8n_name }}.network"
    env: "{{ lookup('jaredhocutt.homelab.container_config', 'env', container='redis') }}"
    secrets: "{{ lookup('jaredhocutt.homelab.container_config', 'secrets', container='redis') }}"
    volumes:
      - "{{ n8n_redis_volume_data }}.volume:/data"
    healthcheck_interval: 5s
    healthcheck_retries: 10
    healthcheck_timeout: 5s
    healthcheck: CMD-SHELL redis-cli ping
    labels: "{{ lookup('jaredhocutt.homelab.container_config', 'labels', container='redis') }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ lookup('jaredhocutt.homelab.container_config', 'quadlet_options', container='redis') }}"
    state: quadlet
  notify: Restart redis for {{ n8n_name }}
  become: true

- name: Create n8n container
  containers.podman.podman_container:
    name: "{{ n8n_name }}"
    image: "{{ n8n_image }}:{{ n8n_image_tag }}"
    network:
      - "{{ n8n_name }}.network"
      - "{{ n8n_traefik_enable | ternary(common_traefik_network ~ '.network', omit) }}"
    env: "{{ lookup('jaredhocutt.homelab.container_config', 'env') }}"
    secrets: "{{ lookup('jaredhocutt.homelab.container_config', 'secrets') }}"
    volumes:
      - "{{ n8n_volume_data }}.volume:/home/node/.n8n"
    publish: "{{ n8n_traefik_enable | ternary(omit, n8n_ports) }}"
    labels: "{{ lookup('jaredhocutt.homelab.container_config', 'labels') }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ lookup('jaredhocutt.homelab.container_config', 'quadlet_options') }}"
    state: quadlet
  notify: Restart {{ n8n_name }}
  become: true

- name: Create worker container
  containers.podman.podman_container:
    name: "{{ n8n_name }}-worker"
    image: "{{ n8n_image }}:{{ n8n_image_tag }}"
    network: "{{ n8n_name }}.network"
    env: "{{ lookup('jaredhocutt.homelab.container_config', 'env', container='worker') }}"
    secrets: "{{ lookup('jaredhocutt.homelab.container_config', 'secrets', container='worker') }}"
    volumes:
      - "{{ n8n_volume_data }}.volume:/home/node/.n8n"
    command: worker
    labels: "{{ lookup('jaredhocutt.homelab.container_config', 'labels', container='worker') }}"
    quadlet_file_mode: "0600"
    quadlet_options: "{{ lookup('jaredhocutt.homelab.container_config', 'quadlet_options', container='worker') }}"
    state: quadlet
  notify: Restart worker for {{ n8n_name }}
  become: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
