---
# handlers file for jaredhocutt.homelab.blaze

- name: Restart {{ blaze_name }}
  ansible.builtin.systemd:
    name: "{{ blaze_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
