---
# handlers file for jaredhocutt.homelab.youtarr

- name: Restart {{ youtarr_name }}
  ansible.builtin.systemd:
    name: "{{ youtarr_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart mariadb for {{ youtarr_name }}
  ansible.builtin.systemd:
    name: "{{ youtarr_name }}-mariadb.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
