---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    pangolin_base_domain: pangolin.localhost
  tasks:
    - name: Include pangolin role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.pangolin
