---

- name: Stop services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  become: true
  failed_when: false
  loop:
    - "{{ vault_name }}.service"
    - "{{ vault_volume_config }}-volume.service"
    - "{{ vault_volume_data }}-volume.service"
    - "{{ vault_volume_logs }}-volume.service"
    - "{{ vault_name }}-network.service"

- name: Destroy containers
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ vault_name }}"

- name: Destroy secrets
  containers.podman.podman_secret:
    name: "{{ item.key }}"
    state: absent
  become: true
  no_log: true
  loop: "{{ vault_secrets_combined | dict2items }}"

- name: Destroy volumes
  containers.podman.podman_volume:
    name: "{{ item }}"
    state: absent
  become: true
  loop:
    - "{{ vault_volume_config }}"
    - "{{ vault_volume_data }}"
    - "{{ vault_volume_logs }}"

- name: Destroy network
  containers.podman.podman_network:
    name: "{{ vault_name }}"
    state: absent
  become: true

- name: Cleanup quadlet files
  ansible.builtin.file:
    path: /etc/containers/systemd/{{ item }}
    state: absent
  become: true
  loop:
    - "{{ vault_name }}.container"
    - "{{ vault_volume_config }}.volume"
    - "{{ vault_volume_data }}.volume"
    - "{{ vault_volume_logs }}.volume"
    - "{{ vault_name }}.network"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
