---

- name: Perform initial server setup
  hosts: pta
  tasks:
    - name: Perform initial server setup
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.server_setup
      tags: [server_setup]

- name: Deploy and configure foundation apps
  hosts: pta
  tasks:
    - name: Install traefik
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.traefik
      tags: [traefik]
  tags: [foundation_apps]

- name: Deploy and configure apps
  hosts: pta
  tasks:
    - name: Install backrest
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.backrest
      tags: [backrest]

    - name: Install bentopdf
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.bentopdf
      tags: [bentopdf]

    - name: Install bentopdf newt
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.newt
      vars:
        newt_name: newt-bentopdf
        newt_attach_to: bentopdf
        newt_secrets: "{{ newt_bentopdf_secrets }}"
        newt_container_secrets: "{{ newt_bentopdf_container_secrets }}"
      tags: [newt, bentopdf]

    - name: Install blaze
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.blaze
      tags: [blaze]

    - name: Install blaze newt
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.newt
      vars:
        newt_name: newt-blaze
        newt_attach_to: blaze
        newt_secrets: "{{ newt_blaze_secrets }}"
        newt_container_secrets: "{{ newt_blaze_container_secrets }}"
      tags: [newt, blaze]

    - name: Install convertx
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.convertx
      tags: [convertx]

    - name: Install it_tools
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.it_tools
      tags: [it_tools]

    - name: Install it_tools newt
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.newt
      vars:
        newt_name: newt-it-tools
        newt_attach_to: it-tools
        newt_secrets: "{{ newt_it_tools_secrets }}"
        newt_container_secrets: "{{ newt_it_tools_container_secrets }}"
      tags: [newt, it_tools]

    - name: Install n8n
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.n8n
      tags: [n8n]

    - name: Install uptime_kuma
      ansible.builtin.import_role:
        name: jaredhocutt.homelab.uptime_kuma
      tags: [uptime_kuma]
