---
# vars file for jaredhocutt.homelab.audiobookshelf

###############################################################################
# Envrionment
###############################################################################

audiobookshelf_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

audiobookshelf_secrets_defaults: {}

audiobookshelf_secrets_combined: >-
  {{ audiobookshelf_secrets_defaults
  | combine(audiobookshelf_secrets, recursive=True) }}

audiobookshelf_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

audiobookshelf_container_labels_defaults: >
  {{ audiobookshelf_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', audiobookshelf_name, audiobookshelf_traefik_host, '80'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

audiobookshelf_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
