---
# vars file for jaredhocutt.homelab.tautulli

###############################################################################
# Envrionment
###############################################################################

tautulli_container_env_defaults: {}

###############################################################################
# Secrets
###############################################################################

tautulli_secrets_defaults: {}

tautulli_secrets_combined: >-
  {{ tautulli_secrets_defaults
  | combine(tautulli_secrets, recursive=True) }}

tautulli_container_secrets_defaults: []

###############################################################################
# Container Labels
###############################################################################

tautulli_container_labels_defaults: >
  {{ tautulli_traefik_enable
  | ternary(lookup('jaredhocutt.homelab.traefik_labels', tautulli_name, tautulli_traefik_host, '8181'), {}) }}

###############################################################################
# Quadlet Options
###############################################################################

tautulli_container_quadlet_options_defaults: "{{ common_quadlet_options_defaults }}"
