---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    uptime_kuma_traefik_enable: false
  tasks:
    - name: Include uptime_kuma role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.uptime_kuma
