---
# handlers file for jaredhocutt.homelab.immich

- name: Restart {{ immich_name }}
  ansible.builtin.systemd:
    name: "{{ immich_name }}.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart machine_learning for {{ immich_name }}
  ansible.builtin.systemd:
    name: "{{ immich_name }}-machine-learning.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart postgres for {{ immich_name }}
  ansible.builtin.systemd:
    name: "{{ immich_name }}-postgres.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true

- name: Restart redis for {{ immich_name }}
  ansible.builtin.systemd:
    name: "{{ immich_name }}-redis.service"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
