---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    calibre_traefik_enable: false
  tasks:
    - name: Include calibre role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.calibre
