---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    prowlarr_traefik_enable: false
  tasks:
    - name: Include prowlarr role
      ansible.builtin.include_role:
        name: jaredhocutt.homelab.prowlarr
