---

server_setup_packages:
  - chezmoi
  - cockpit
  - cockpit-files
  - cockpit-networkmanager
  - cockpit-podman
  - cockpit-storaged
  - cockpit-system
  - curl
  - dnf5-plugin-automatic
  - git
  - gnupg2
  - htop
  - net-tools
  - pcp
  - python3-pcp
  - rsync
  - stow
  - tmux
  - unzip
  - vim
  - wget
  - zsh

server_setup_enabled_services:
  - cockpit.socket
  - pmlogger.service
